# Always validate the PR title, and ignore the commits
titleOnly: true
# By default types specified in commitizen/conventional-commit-types is used.
# See: https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json
# You can override the valid types
types:
  - feat         # A new feature
  - fix          # Bug Fixes
  - docs         # Documentation
  - style        # Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
  - refactor     # A code change that neither fixes a bug nor adds a feature
  - perf         # A code change that improves performance
  - test         # Adding missing tests or correcting existing tests
  - build        # Changes that affect the build system or external dependencies (example scopes: Next.js, npm, webpack)
  - ci           # Changes to our CI configuration files and scripts (example scopes: GitHub Action, Circle)
  - chore        # Other changes that don't modify src or test files
  - revert       # Reverts a previous commit
