name: Conventional Release Labels

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          type_labels: '{"feat": "Feature", "fix": "Fix", "ci": "CI", "docs": "Documentation", "test": "Tests", "refactor": "Refactoring", "perf": "Performance Improvements", "build": "Build", "chore": "Chore"}'
          ignored_types: '["revert", "release"]'
          ignore_label: Ignore For Release
